### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by dmethvin** [Fordi/eyegame#1]
None of the files indicate the license, ideally there would be a LICENSE file.

**Comment by iankronquist** [comment]
A readme would be nice too.

**Comment by jshemas** [comment]
+1 (For both a license and readme)

**Comment by Fordi** [comment]
Ok.  Dropped in a CC/BY/SA 4.0 and a short description of what it is and what it's for.  I'll get some more work done on the thing whenever I get a minute.  I'll use the ticketing system to make tasks for myself.
